CREATE OR REPLACE PROCEDURE TEST
AS
    X NUMBER := 23;
BEGIN
    
    IF X>0 THEN
    DBMS_OUTPUT.PUT_LINE('IT IS +VE NUMBER');
    ELSE
    DBMS_OUTPUT.PUT_LINE('ITS A -VE NUMBER');
    END IF;
END;
/


SET SERVEROUTPUT ON;

EXECUTE TEST